### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arjunsatarkar** [emilk/eframe_template#109]
If the idea is to take this template, make modifications, and then build on that, shouldn't it have a license?

**Comment by c-git** [comment]
I see your point, but if they authors want to give full control to the person using the code to choose their own licence which licence should they use to achieve that and not "dirty" the template with a licence file. @arjunsatarkar by any chance do you know?

**Comment by arjunsatarkar** [comment]
If the idea is literally no conditions then [CC0](https://creativecommons.org/public-domain/cc0/), I guess? It could be MIT and just require attribution.

**Comment by c-git** [comment]
Do you feel that adding it to the readme would be enough?

**Comment by arjunsatarkar** [comment]
Yeah, there's no requirement that it has to be in a separate file - the README should work fine.

**Comment by c-git** [comment]
Thanks for the feedback, we'll see what the maintainers think

**Comment by apirogov** [comment]
Legally, if there is no license, then by default "all rights are reserved". Just because something is published, it does not mean it can be freely used. For private hobby things this might not matter much, but for work-related usage this is very much a serious concern. But uploading something to the internet it's not automatically "public domain", and one can also not actually *put* something into the public domain actively in some countries.

That's why, to make this template legally "safe for work", I agree that [CC0](https://creativecommons.org/public-domain/cc0/) or something similar, like e.g. [Unlicense](https://choosealicense.com/licenses/unlicense/) should be added to this repository (in case it is intended to be used as-if it was public domain)

**Comment by c-git** [comment]
Yeah I see your point. Makes sense but they seem to have very low bandwidth and haven't been able to get to this. Worst case you should be able to look at this like a pattern and just do your own thing if it's for a work project. There isn't anything intrinsically necessary to copy from here.

**Comment by 9SMTM6** [comment]
This is solved on the current master branch.
