### ISSUE TITLE
CI Use of actions-rs

### ISSUE THREAD

**Issue by c-git** [emilk/eframe_template#134]
Hi,

Thanks for all the work on this template, it is a great starting point.

I noticed that the [action](https://github.com/actions-rs/toolchain) used to setup rust is no longer actively maintained and has been officially archived by the owner.

![image](https://github.com/emilk/eframe_template/assets/43485962/fe3ee4c6-f1ef-4235-8580-b134d81c1c31)

On my other projects I use the [actions-rust-lang/setup-rust-toolchain](https://github.com/actions-rust-lang/setup-rust-toolchain) action and plan to also try to update my copy of the workflow but wanted to know if a pull request for this would make sense. Don't have the bandwidth to do it right now but just checking in case there is a reason I shouldn't make a PR.

**Comment by emilk** [comment]
Closed by https://github.com/emilk/eframe_template/pull/139

**Comment by 9SMTM6** [comment]
@emilk that PR only removed a single use of actions-rs. It still used in a bunch of other places.

I'm currently testing a pipeline that also drops cross. It was my understanding that cross was required due to us targeting musl without running in a musl environment. Since that PR dropped musl, and assuming that no other issues are created by dropping it, this might massively simplify CI.
